version: "3.8"

services:
    flask-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: flask-app
        ports:
            - "5000:5000"
        environment:
            - FLASK_ENV=production
            - FLASK_APP=main.py
        volumes:
            - .:/app
        restart: always
        networks:
            - webnet

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./static:/usr/share/nginx/html/static
        depends_on:
            - flask-app
        restart: always
        networks:
            - webnet

networks:
    webnet:
